package com.smartservice.controller;
import com.smartservice.model.*; import com.smartservice.repository.UserRepository; import com.smartservice.service.*; import jakarta.servlet.http.HttpSession; import org.springframework.http.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/auth") @CrossOrigin(origins="http://localhost:5173",allowCredentials="true")
public class AuthController {
 private final UserRepository users; private final PasswordEncoder encoder; private final OtpService otp; private final EmailService email;
 public AuthController(UserRepository u,PasswordEncoder e,OtpService o,EmailService m){users=u;encoder=e;otp=o;email=m;}
 @PostMapping("/send-otp") public Map<String,String> send(@RequestBody Map<String,String> b){String em=b.getOrDefault("email","").trim().toLowerCase(); boolean reg="true".equalsIgnoreCase(b.get("register")); if(em.isBlank())throw ex("Email is required",HttpStatus.BAD_REQUEST); if(reg && users.existsByEmailIgnoreCase(em))throw ex("Account already exists",HttpStatus.CONFLICT); if(!reg && users.findByEmailIgnoreCase(em).isEmpty())throw ex("No account found for this email",HttpStatus.NOT_FOUND); String code=otp.generate(em); email.sendOtp(em,code); return Map.of("message","OTP sent");}
 @PostMapping("/verify-otp") public Map<String,Object> verify(@RequestBody Map<String,String> b,HttpSession s){String em=b.getOrDefault("email","").trim().toLowerCase(),code=b.getOrDefault("otp","").trim(); boolean reg="true".equalsIgnoreCase(b.get("register")); if(!otp.verify(em,code))throw ex("Invalid or expired OTP",HttpStatus.UNAUTHORIZED); User u=users.findByEmailIgnoreCase(em).orElse(null); if(u==null && reg){String name=b.getOrDefault("name","Customer").trim();u=users.save(User.builder().name(name).email(em).password(encoder.encode(UUID.randomUUID().toString())).role(Role.CUSTOMER).build());} if(u==null)throw ex("Account not found",HttpStatus.UNAUTHORIZED); s.setAttribute("userId",u.getId());s.setAttribute("userRole",u.getRole().name());s.setAttribute("email",u.getEmail());return view(u);}
 @GetMapping("/me") public Map<String,Object> me(HttpSession s){Object id=s.getAttribute("userId");if(id==null)throw ex("Not logged in",HttpStatus.UNAUTHORIZED);return view(users.findById((Long)id).orElseThrow(()->ex("User not found",HttpStatus.UNAUTHORIZED)));}
 @PostMapping("/logout") public Map<String,String> logout(HttpSession s){s.invalidate();return Map.of("message","Logged out");}
 private Map<String,Object> view(User u){return Map.of("id",u.getId(),"name",u.getName(),"email",u.getEmail(),"role",u.getRole().name());}
 private RuntimeException ex(String m,HttpStatus st){return new ApiException(m,st);} public static class ApiException extends RuntimeException{final HttpStatus status;ApiException(String m,HttpStatus s){super(m);status=s;}public HttpStatus getStatus(){return status;}}
}
