spring.application.name=smart-service-management-portal

server.port=${PORT:8080}

spring.datasource.url=jdbc:h2:mem:smartservice
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true

# Resend Email API
resend.api-key=${RESEND_API_KEY:}
resend.from=${RESEND_FROM:onboarding@resend.dev}