import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import axios from 'axios';
import {LayoutDashboard,Ticket,Users,BarChart3,Settings,LogOut,Plus,Search,ShieldCheck,UserRound,CheckCircle2,Clock3,AlertTriangle} from 'lucide-react';
import {PieChart,Pie,Cell,Tooltip,Legend,BarChart,Bar,XAxis,YAxis,CartesianGrid,LineChart,Line,ResponsiveContainer} from 'recharts';
import './styles.css';
const api=axios.create({baseURL:'/api',withCredentials:true});
function App(){const[user,setUser]=useState(null),[mode,setMode]=useState('login'),[otpSent,setOtpSent]=useState(false),[email,setEmail]=useState(''),[otp,setOtp]=useState(''),[name,setName]=useState(''),[msg,setMsg]=useState(''),[loading,setLoading]=useState(false),[tickets,setTickets]=useState([]),[tab,setTab]=useState('dashboard'),[showCreate,setShowCreate]=useState(false);
 const load=async()=>{try{setUser((await api.get('/auth/me')).data)}catch{setUser(null)}}; useEffect(()=>{load()},[]);
 const sendOtp=async()=>{setLoading(true);setMsg('');try{await api.post('/auth/send-otp',{email,name,register:mode==='register'});setOtpSent(true);setMsg('OTP sent. If SMTP is not configured, check the backend console.')}catch(e){setMsg(e.response?.data?.message||'Unable to send OTP')}finally{setLoading(false)}};
 const verify=async()=>{setLoading(true);try{const r=await api.post('/auth/verify-otp',{email,otp,name,register:mode==='register'});setUser(r.data);setTab('dashboard')}catch(e){setMsg(e.response?.data?.message||'Invalid OTP')}finally{setLoading(false)}};
 const logout=async()=>{await api.post('/auth/logout');setUser(null);setOtpSent(false);setOtp('')};
 const refresh=async()=>{try{setTickets((await api.get('/tickets')).data)}catch{setTickets([])}}; useEffect(()=>{if(user)refresh()},[user,tab]);
 const create=async f=>{await api.post('/tickets',f);setShowCreate(false);refresh()};
 if(!user)return <Auth mode={mode} setMode={setMode} email={email} setEmail={setEmail} name={name} setName={setName} otp={otp} setOtp={setOtp} otpSent={otpSent} sendOtp={sendOtp} verify={verify} msg={msg} loading={loading}/>;
 return <Shell user={user} tab={tab} setTab={setTab} logout={logout} tickets={tickets} setTickets={setTickets} refresh={refresh} showCreate={showCreate} setShowCreate={setShowCreate} create={create}/>}
function Auth(p){return <div className="auth"><div className="auth-card"><div className="brand"><ShieldCheck/> Smart Service</div><h1>{p.mode==='login'?'Welcome back':'Create customer account'}</h1><p className="muted">Secure access using email OTP</p>{p.mode==='register'&&<input placeholder="Full name" value={p.name} onChange={e=>p.setName(e.target.value)}/>}<input type="email" placeholder="Email address" value={p.email} onChange={e=>p.setEmail(e.target.value)}/>{p.otpSent&&<input placeholder="6-digit OTP" maxLength="6" value={p.otp} onChange={e=>p.setOtp(e.target.value)}/>}<button onClick={p.otpSent?p.verify:p.sendOtp} disabled={p.loading}>{p.loading?'Please wait...':p.otpSent?'Verify & Continue':'Send OTP'}</button><div className="msg">{p.msg}</div><button className="link" onClick={()=>{p.setMode(p.mode==='login'?'register':'login');p.setOtpSent(false);p.setMsg('')}}>{p.mode==='login'?'New customer? Register':'Already have an account? Login'}</button><div className="demo"><b>Demo emails</b><br/>Admin: admin@smartservice.com<br/>Employee: employee@smartservice.com<br/>Customer: customer@smartservice.com<br/><small>OTP is emailed when SMTP is configured; otherwise it is printed in the backend console.</small></div></div></div>}
function Shell({user,tab,setTab,logout,tickets,setTickets,refresh,showCreate,setShowCreate,create}){const nav=user.role==='ADMIN'?['dashboard','tickets','users','reports','settings']:['dashboard','tickets','settings'];return <div className="app"><aside><div className="brand"><ShieldCheck/> Smart Service</div><div className="role">{user.role}</div>{nav.map(n=><button className={tab===n?'active':''} onClick={()=>setTab(n)} key={n}>{n==='dashboard'?<LayoutDashboard/>:n==='tickets'?<Ticket/>:n==='users'?<Users/>:n==='reports'?<BarChart3/>:<Settings/>}{n[0].toUpperCase()+n.slice(1)}</button>)}<button className="logout" onClick={logout}><LogOut/> Logout</button></aside><main><header><div><h2>{tab[0].toUpperCase()+tab.slice(1)}</h2><span className="muted">Hello, {user.name}</span></div><div className="profile"><UserRound/> {user.email}</div></header>{tab==='dashboard'&&<Dashboard user={user} tickets={tickets}/>} {tab==='tickets'&&<Tickets user={user} tickets={tickets} setTickets={setTickets} refresh={refresh} setShowCreate={setShowCreate}/>} {tab==='users'&&<UsersPage/>}{tab==='reports'&&<Reports/>}{tab==='settings'&&<SettingsPage user={user}/>} {showCreate&&<CreateModal onClose={()=>setShowCreate(false)} onCreate={create}/>}</main></div>}
function Dashboard({user,tickets}){const stats=[['Total',tickets.length,Ticket],['Open',tickets.filter(x=>x.status==='OPEN').length,Clock3],['In Progress',tickets.filter(x=>x.status==='IN_PROGRESS').length,AlertTriangle],['Resolved / Closed',tickets.filter(x=>['RESOLVED','CLOSED'].includes(x.status)).length,CheckCircle2]];return <><div className="cards">{stats.map(([a,b,I])=><div className="card" key={a}><I/><span>{a}</span><strong>{b}</strong></div>)}</div><section className="panel"><div className="panel-head"><h3>{user.role==='CUSTOMER'?'My Recent Tickets':user.role==='EMPLOYEE'?'Tickets Assigned To Me':'All Recent Tickets'}</h3></div><TicketTable tickets={tickets.slice(0,8)} admin={user.role==='ADMIN'} employee={user.role==='EMPLOYEE'}/></section></>}
function Tickets({user,tickets,setTickets,refresh,setShowCreate}){const[q,setQ]=useState('');const data=tickets.filter(t=>(t.title||'').toLowerCase().includes(q.toLowerCase())||(t.ticketNumber||'').toLowerCase().includes(q.toLowerCase()));return <section className="panel"><div className="panel-head"><div className="search"><Search/><input placeholder="Search tickets..." value={q} onChange={e=>setQ(e.target.value)}/></div>{user.role==='CUSTOMER'&&<button onClick={()=>setShowCreate(true)}><Plus/> New Ticket</button>}</div><TicketTable tickets={data} admin={user.role==='ADMIN'} employee={user.role==='EMPLOYEE'} setTickets={setTickets} refresh={refresh}/></section>}
function TicketTable({tickets,admin,employee,setTickets,refresh}){const[employees,setEmployees]=useState([]);useEffect(()=>{if(admin)api.get('/users?role=EMPLOYEE').then(r=>setEmployees(r.data)).catch(()=>{})},[admin]);const update=async(id,status)=>{await api.patch('/tickets/'+id+'/status',{status});refresh?.()};const assign=async(id,employee)=>{await api.patch('/tickets/'+id+'/assign',{employee});refresh?.()};if(!tickets.length)return <div className="empty">No tickets found.</div>;return <div className="table-wrap"><table><thead><tr><th>Ticket</th><th>Customer</th><th>Issue</th><th>Priority</th><th>Assigned To</th><th>Status</th>{employee&&<th>Update</th>}</tr></thead><tbody>{tickets.map(t=><tr key={t.id}><td><b>{t.ticketNumber}</b></td><td>{t.customerName}<small>{t.customerEmail}</small></td><td>{t.title}<small>{t.description}</small></td><td><span className={'badge '+String(t.priority).toLowerCase()}>{t.priority}</span></td><td>{admin?<select value={t.assignedEmployee||''} onChange={e=>assign(t.id,e.target.value)}><option value="">Unassigned</option>{employees.map(e=><option key={e.id} value={e.email}>{e.name} — {e.email}</option>)}</select>:t.assignedEmployee||'Unassigned'}</td><td><span className="status">{String(t.status).replace('_',' ')}</span></td>{employee&&<td><select value={t.status} onChange={e=>update(t.id,e.target.value)}><option>ASSIGNED</option><option>IN_PROGRESS</option><option>RESOLVED</option><option>CLOSED</option></select></td>}</tr>)}</tbody></table></div>}
function CreateModal({onClose,onCreate}){const[f,setF]=useState({title:'',description:'',category:'IT',priority:'MEDIUM'});return <div className="modal"><div className="modal-card"><h2>Create Service Ticket</h2><input placeholder="Issue title" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/><textarea placeholder="Describe the problem" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/><input placeholder="Category" value={f.category} onChange={e=>setF({...f,category:e.target.value})}/><select value={f.priority} onChange={e=>setF({...f,priority:e.target.value})}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select><div className="actions"><button className="secondary" onClick={onClose}>Cancel</button><button onClick={()=>onCreate(f)}>Submit Ticket</button></div></div></div>}
function UsersPage(){const[users,setUsers]=useState([]),[form,setForm]=useState({name:'',email:''}),[msg,setMsg]=useState('');const load=()=>api.get('/users').then(r=>setUsers(r.data));useEffect(load,[]);const add=async e=>{e.preventDefault();setMsg('');try{await api.post('/users/employees',form);setForm({name:'',email:''});setMsg('Employee account created successfully.');load()}catch(x){setMsg(x.response?.data?.message||'Could not create employee')}};return <><section className="panel"><div className="panel-head"><div><h3>Employee Management</h3><p className="muted">Only administrators can create employee accounts.</p></div></div><form className="inline-form" onSubmit={add}><input placeholder="Employee name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input type="email" placeholder="Employee email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><button><Plus/> Add Employee</button></form><div className="msg">{msg}</div></section><section className="panel"><h3>Customers & Employees</h3><div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td><span className="status">{u.role}</span></td></tr>)}</tbody></table></div></section></>}
function Reports(){const[data,setData]=useState(null);useEffect(()=>{api.get('/reports').then(r=>setData(r.data)).catch(()=>setData(null))},[]);if(!data)return <section className="panel"><h3>Service Reports</h3><p className="muted">Loading report data...</p></section>;const status=Object.entries(data.status).map(([name,value])=>({name,value})),priority=Object.entries(data.priority).map(([name,value])=>({name,value})),employees=Object.entries(data.employees).map(([name,value])=>({name:name.split('@')[0],value}));return <div className="report-grid"><section className="panel chart"><h3>Tickets by Status</h3><ResponsiveContainer width="100%" height={280}><PieChart><Pie data={status} dataKey="value" nameKey="name" outerRadius={90} label>{status.map((x,i)=><Cell key={i}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></section><section className="panel chart"><h3>Tickets by Priority</h3><ResponsiveContainer width="100%" height={280}><BarChart data={priority}><CartesianGrid/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value"/></BarChart></ResponsiveContainer></section><section className="panel chart full"><h3>Employee Workload</h3><ResponsiveContainer width="100%" height={280}><BarChart data={employees}><CartesianGrid/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value"/></BarChart></ResponsiveContainer></section><section className="panel chart full"><h3>Monthly Ticket Trend</h3><ResponsiveContainer width="100%" height={280}><LineChart data={data.monthly}><CartesianGrid/><XAxis dataKey="month"/><YAxis allowDecimals={false}/><Tooltip/><Line type="monotone" dataKey="count"/></LineChart></ResponsiveContainer></section><div className="cards full"><div className="card"><Ticket/><span>Total</span><strong>{data.total}</strong></div><div className="card"><AlertTriangle/><span>Unassigned</span><strong>{data.unassigned}</strong></div></div></div>}
function SettingsPage({user}){return <section className="panel"><h3>My Profile</h3><div className="profile-box"><b>{user.name}</b><span>{user.email}</span><span>Role: {user.role}</span></div></section>}
createRoot(document.getElementById('root')).render(<App/>);
